import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
    <div className="flex gap-2 ">
      {/* left side */}
      <div className="w-1/5 bg-amber-100">
        <h1>left side</h1>
      </div>
      {/* right side */}
       <div className="3/5">
       <h1>
        this is header
      </h1>
      <div className="h-screen">

        {children}
      </div>
        <h1>
            this is footer
        </h1>
     </div>
    </div>
        </body>
    </html>
  );
}
